agent:
  model:
    # name: ollama/llama2  
    # name: ollama/qwen2.5-coder:14b
    name: ollama/qwen2.5-coder:7b
    api_base: http://localhost:11434
    per_instance_cost_limit: 0   
    total_cost_limit: 0
    per_instance_call_limit: 100
    max_input_tokens: 0  
